---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templatelink1: 'https://raw.githubusercontent.com/nitinpokharna/webbot/master/qna/azuredeploy.json'
    #paramslink1: 'https://raw.githubusercontent.com/nitinpokharna/webbot/master/qna/azuredeploy.parameters.json'
    templateLink: 'https://raw.githubusercontent.com/nitinpokharna/webbot/master/azuredeploy.json'
    #paramsLink: 'https://raw.githubusercontent.com/nitinpokharna/webbot/master/azuredeploy.parameters.json'
    var_zipUrl: "https://connectorprod.blob.core.windows.net/bot-packages/csharp-abs-webapp_qnabot_precompiled.zip"
    var_botId: "nitinptestchatbot"
    var_location: "West US"
    var_kind: "sdk"
    var_sku: "F0"
    var_siteName: "nitinptestchatbot"
    var_appId: "cd3b2269-5e08-4afe-bdbc-ea83703c7b3b"
    var_appSecret: "vC/FoAE@9rqCvH|l"
    var_createNewStorage: true
    var_storageAccountName: "nitinptestchatbotad0f"
    var_storageAccountResourceId: ""
    var_botEnv: "prod"
    var_useAppInsights: true
    var_appInsightsLocation: "East US"
    var_createServerFarm: true
    var_serverFarmId: "/subscriptions/7baa9f2b-0857-4063-a952-a2ff81a3fc80/resourceGroups/nitindem/providers/Microsoft.Web/serverfarms/nitinapp"
    var_serverFarmLocation: "West US"
    var_azureWebJobsBotFrameworkDirectLineSecret: ""
    var_name: "nitinqna"
    var_appName: "nitinqnanq"
    var_location2: "East US"
    var_location3: "Central US"
    var_location4: "West US"
    var_sku2: "free"
    var_searchHostingMode: "default"
   
  tasks:
  - name: Creating QNA maker
    azure_rm_deployment:
        state: present
        resource_group_name: 'nitindem'
        parameters:
          name: 
              value: '{{ var_name }}'
          location2: 
              value: '{{ var_location2 }}'
          location3: 
              value: '{{ var_location3 }}'
          location4: 
              value: '{{ var_location4 }}'
          sku: 
              value: '{{ var_sku }}'
          sku2: 
              value: '{{ var_sku2 }}'
          searchHostingMode: 
              value: '{{ var_searchHostingMode }}'
        template_link: '{{ templatelink1 }}'
        
  - name: Creating webapp bot
    azure_rm_deployment:
        state: present
        resource_group_name: 'nitindem'
        parameters:
          zipUrl: 
              value: '{{ var_zipUrl }}'
          botId: 
              value: '{{ var_botId }}'
          location: 
              value: '{{ var_location }}'
          kind: 
              value: '{{ var_kind }}'
          sku: 
              value: '{{ var_sku }}'
          sitename: 
              value: '{{ var_sitename }}'
          appId: 
              value: '{{ var_appId }}'
          appSecret: 
              value: '{{var_appSecret }}'
          createNewStorage: 
              value: '{{ var_createNewStorage }}'
          storageAccountName: 
              value: '{{ var_storageAccountName }}'
          storageAccountResourceId: 
              value: '{{ var_storageAccountResourceId }}'
          botEnv: 
              value: '{{ var_botEnv}}'
          useAppInsights: 
              value: '{{ var_useAppInsights }}'
          createServerFarm: 
              value: '{{ var_createServerFarm }}'
          serverFarmId: 
              value: '{{ var_serverFarmId }}'
          serverFarmLocation: 
              value: '{{ var_serverFarmLocation }}'
          azureWebJobsBotFrameworkDirectLineSecret: 
              value: '{{ var_azureWebJobsBotFrameworkDirectLineSecret }}'
        template_link: '{{ templateLink }}'
